package interfaces;

/**
 * Interface for displaying to the user the extracted information related to his/her query.
 */
public interface IFrontEnd 
{
	/**
	 * Given a query generated by the user, display its related information. For example, given
	 * the query "iphone steve jobs", display the N most salient dimensions associated with
	 * this query along with their sentiment scores.
	 * 
	 * @param query The query entered by the user
	 * 
	 * @return Extracted result as a String
	 */
	String showResults(IQuery query);
}
